### ISSUE TITLE
API Key authorization errors when integrating with API Umbrella 0.11

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#899]
Since experimenting with API Umbrella 0.11, we have encountered several errors related to the API Umbrella user API Key not being authorized to perform certain functions. For example, when setting up a new developer environment, we create an API Umbrella superuser and API Key, but the API Key is not authorized to create new users on API Umbrella.

# Steps to reproduce
1. Log in to API Umbrella (0.11 @ nightly.umbrella.apinf.io)
2. Go to Users -> Admin Accounts
3. Create a new admin user
  * check 'superuser' box
4. Go to Users -> API Users
5. Click 'Add New API User'
6. Create new API user with same email as admin user
  * Under Permissions -> Roles, add `api-umbrella-key-creator`
7. Sign-in with new Admin user
8. Get `API Key` and `Admin API Token` for new user
9. Add API Key and Admin API Token to settings.json
10. Launch Apinf
11. Register a new user

# Observed behavior
When registering a new user, the screen displays an **Internal server error** message. In the server console, the following error appears:

```sh
Exception while invoking method 'ATCreateUserServer' Error
     at new ApiUmbrellaError (packages/brylie_api-umbrella/server/apiUmbrellaError.js:33:1)
     at Object.self.adminApi.v1.apiUsers.createUser (packages/brylie_api-umbrella/server/apiUmbrellaWeb.js:275:1)
   ...
```

The main issue is related to the following line `Object.self.adminApi.v1.apiUsers.createUser (packages/brylie_api-umbrella/server/apiUmbrellaWeb.js:275:1`, where we are trying to create an user on API Umbrella. FWIW, [that part of our integration code hasn't changed since 12 November 2015](https://github.com/apinf/meteor-api-umbrella/blame/master/server/apiUmbrellaWeb.js#L275).

# Related
* See [issue #217 on API Umbrella backlog](https://github.com/NREL/api-umbrella/issues/217)
* Related issue on nightly #893
* Originally reported in the [User Profile testing task](https://github.com/apinf/api-umbrella-dashboard/issues/891)

**Comment by brylie** [comment]
@jykae please use this issue to track the integration errors.

**Comment by brylie** [comment]
@bajiat lets use this issue to track the recent API Umbrella 0.11 integration errors.

**Comment by bajiat** [comment]
@brylie Ok, thanks! Shall we assign this to @jykae?

**Comment by brylie** [comment]
@jykae will you please self-assign?

**Comment by jykae** [comment]
assigned and in progress

**Comment by jykae** [comment]
This seems to happen only in nightly as nightly.umbrella has been reinstalled and is down. I successfully registered new user on apinf.io

**Comment by brylie** [comment]
@jykae please follow the steps to reproduce after installing a fresh API Umbrella 0.11 instance. We were getting the errors on the previous 0.11 installation.

Also, be sure to test with newly created users.

**Comment by ashakunt** [comment]
@Alapan @saralavanip Once this bug is fixed, you can continue with your tasks.

**Comment by jykae** [comment]
We are rolling back nightly Umbrella to previous state and testing that the key rights are correct.

**Comment by jykae** [comment]
This was related to wrong settings in nightly.apinf.io Giving settings.json on deployment command did not override the existing Settings object in DB. I got in with my old account that existed on nightly and changed settings to point nightly Umbrella and verified that registration works now.

**Comment by jykae** [comment]
@Alapan @saralavanip please let me know if you are able to register now to nightly. @brylie was also able to do it so nightly registration should work now I think this can be closed then.

**Comment by Alapan** [comment]
@jykae Yes I was able to register now.

**Comment by Alapan** [comment]
@jykae However, I am still unable to login/register on my local application. I tried git pull in the api-umbrella-dashboard, but it appears no changes were made there. Do I have to change any file to make it work on my localhost application? 

The error on the server console is still the same:
Exception while invoking method 'ATCreateUserServer' TypeError: Cannot read property 'length' of null

**Comment by jykae** [comment]
Worked the settings file together via chat. @Alapan verified that local development works now against nightly Umbrella.

**Comment by brylie** [comment]
Great work @jykae :-)

**Comment by bajiat** [comment]
Thanks for solving the issue @jykae

2016-03-02 10:36 GMT+02:00 Brylie Christopher Oxley <
notifications@github.com>:

> Great work @jykae <https://github.com/jykae> :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apinf/api-umbrella-dashboard/issues/899#issuecomment-191128384>
> .
>



-- 
---------
*Taija Björklund*
p. 040 5177 969
taija.bjorklund@gmail.com
www.linkedin.com/in/taijabjorklund

**Comment by saralavanip** [comment]
@jykae , Verified and was successful in Sign up/ Register on https://nightly.apinf.io

**Comment by Alapan** [comment]
@jykae Sign In/Register was working correctly in the local environment.
